service: keras

provider:
  name: aws
  region: us-east-1
  runtime: python3.6
  stage: dev

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
       Fn::Join:
         - ""
         - - "arn:aws:s3:::"
           - ${self:provider.environment.BUCKET}
           - "/*"
    - Effect: Allow
      Action:
        - s3:*
      Resource:
       Fn::Join:
         - ""
         - - "arn:aws:s3:::"
           - ${self:provider.environment.BUCKET2}
           - "/*"

  environment:
    BUCKET: kers-demo-mady009
    BUCKET2: keras-background-model

functions:
  upload:
    handler: upload.uploadHandler
    timeout: 30
    events:
      - http:
          path: upload
          method: post

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true

resources:
  Resources:
    SageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET}
